drop table if exists Db_HomeInformation;

drop table if exists HOLD_SEQ;

drop table if exists PUB_OPTIONALHISTORYSTOCK;

drop table if exists PUB_SEARCHHISTORYSTOCK;

drop table if exists PUB_STOCKLIST;

drop table if exists PUB_USERS;

/*==============================================================*/
/* Table: Db_HomeInformation                                    */
/*==============================================================*/
CREATE TABLE Db_HomeInformation (
USERID  TEXT(9000) NOT NULL,
TITLE  TEXT(9000),
STOCK  TEXT(9000),
DATE  TEXT(9000),
EXCOLUMN00  TEXT(9000),
EXCOLUMN01  TEXT(9000),
EXCOLUMN02  TEXT(9000),
EXCOLUMN03  TEXT(9000),
EXCOLUMN04  TEXT(9000),
EXCOLUMN05  TEXT(9000),
EXCOLUMN06  TEXT(9000),
EXCOLUMN07  TEXT(9000),
EXCOLUMN08  TEXT(9000),
EXCOLUMN09  TEXT(9000)
);



/*==============================================================*/
/* Table: HOLD_SEQ                                              */
/*==============================================================*/
CREATE TABLE HOLD_SEQ (
CODE  TEXT NOT NULL,
STOCKHOLDON  TEXT,
PRIMARY KEY (CODE),
CONSTRAINT CODE UNIQUE (CODE)
);



/*==============================================================*/
/* Table: PUB_OPTIONALHISTORYSTOCK                              */
/*==============================================================*/
CREATE TABLE PUB_OPTIONALHISTORYSTOCK (
STOCKCODE  TEXT(40),
NAME  TEXT(40),
HOT  TEXT(40),
HOLD  TEXT(40),
DATE  TEXT(40),
EXCOLUMN00  TEXT(40),
EXCOLUMN01  TEXT(40),
EXCOLUMN02  TEXT(40),
EXCOLUMN03  TEXT(40),
EXCOLUMN04  TEXT(40),
EXCOLUMN05  TEXT(40),
EXCOLUMN06  TEXT(40),
EXCOLUMN07  TEXT(40),
EXCOLUMN08  TEXT(40),
EXCOLUMN09  TEXT(40)
);



/*==============================================================*/
/* Table: PUB_SEARCHHISTORYSTOCK                                */
/*==============================================================*/
CREATE TABLE [PUB_SEARCHHISTORYSTOCK] (
  [STOCKCODE] TEXT(40) NOT NULL,
  [NAME] TEXT(40),
  [HOT] TEXT(40),
  [HOLD] TEXT(40),
  [DATE] TEXT(40),
  [EXCOLUMN00] TEXT(40),
  [EXCOLUMN01] TEXT(40),
  [EXCOLUMN02] TEXT(40),
  [EXCOLUMN03] TEXT(40),
  [EXCOLUMN04] TEXT(40),
  [EXCOLUMN05] TEXT(40),
  [EXCOLUMN06] TEXT(40),
  [EXCOLUMN07] TEXT(40),
  [EXCOLUMN08] TEXT(40),
  [EXCOLUMN09] TEXT(40),
  CONSTRAINT [sqlite_autoindex_PUB_SEARCHHISTORYSTOCK_1] PRIMARY KEY ([STOCKCODE] ASC));



/*==============================================================*/
/* Table: PUB_STOCKLIST                                         */
/*==============================================================*/
CREATE TABLE PUB_STOCKLIST (
ID  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
ISHOLD  TEXT,
STOCKCODE  TEXT(40),
NAME  TEXT(40),
PRICECHANGEVALUE  TEXT(40),
PRICECHANGERATIO  TEXT(40),
CURRENTPRICE  REAL(40),
BEFORECLOSEPRICE  REAL(40),
TODAYOPENPRICE  REAL(40),
TIME  TEXT(40),
DATE  TEXT(40),
HIGH  TEXT(40),
LOW  TEXT(40),
PLATE  TEXT(40),
PRESENTAMOUNT  TEXT(40),
TOTALVOLUME  TEXT(40),
TOTALPRICE  REAL(40),
INFLOWMONEY  TEXT(40),
OUTFLOWMONEY  TEXT(40),
BUYORDER  TEXT(40),
SELLORDER  TEXT(40),
TURNOVER  TEXT(40),
TRADE  TEXT(40),
TYPE  TEXT(40),
TRADECODE  TEXT(40),
PEG  TEXT(40),
FLOWEQUITY  TEXT(40),
TOTALEQUITY  TEXT(40),
PBR  TEXT(40),
INDYSTRYUPANDDOWN  TEXT(40),
EQUIVALENTRATIO  TEXT(40),
BUY1  TEXT(40),
BUY2  TEXT(40),
BUY3  TEXT(40),
BUY4  TEXT(40),
BUY5  TEXT(40),
BUY1AMOUNT  TEXT(40),
BUY2AMOUNT  TEXT(40),
BUY3AMOUNT  TEXT(40),
BUY4AMOUNT  TEXT(40),
BUY5AMOUNT  TEXT(40),
SELL1  TEXT(40),
SELL2  TEXT(40),
SELL3  TEXT(40),
SELL4  TEXT(40),
SELL5  TEXT(40),
SELL1AMOUNT  TEXT(40),
SELL2AMOUNT  TEXT(40),
SELL3AMOUNT  TEXT(40),
SELL4AMOUNT  TEXT(40),
SELL5AMOUNT  TEXT(40),
isSelfChoice  TEXT(40),
isHoldStock  TEXT(40),
apperHoldStock  TEXT(40),
MKT_VAL  TEXT(40),
SECU_ACC  TEXT(40),
SHARE_BLN  TEXT(40),
SHARE_AVL  TEXT(40),
SHARE_QTY  TEXT(40),
PROFIT_RATIO  TEXT(40),
MARKET  TEXT(40),
BRANCH  TEXT,
MKT_PRICE  TEXT,
SECU_CODE  TEXT,
INCOME_AMT  TEXT,
SECU_NAME  TEXT,
CURRENT_COST  TEXT
);


/*==============================================================*/
/* Table: PUB_USERS                                             */
/*==============================================================*/
CREATE TABLE [PUB_USERS] (
    USERNAME VARCHAR(50),
    NICKNAME VARCHAR(50),


  [TRADESCNO] TEXT,
  [USERID] INTEGER,
  [USERTYPE] TEXT,
  [PASSWORD] TEXT,
  [SCNO] INTEGER,
  [ISLOGIN] TEXT,
  [ISREGISTER] TEXT,
  [REALAUTH] TEXT,
  [PICKNAME] TEXT,
  [PINYIN] TEXT,
  [SIGNATURE] TEXT,
  [SEX] TEXT,
  [PHOTO] TEXT,
  [ZOOMPHOTO] TEXT,
  [POOLADDRSS] TEXT,
  [POOLADDRESS] TEXT,
  [BIRTHDATE] TEXT,
  [SERIALNUMBER] INTEGER,
  [HOMETOWN] TEXT,
  [RELIGIOUSVIEW] TEXT,
  [MIDDLESCHOOL] TEXT,
  [BGPICTURE] TEXT,
  [MOUNT] TEXT,
  [REGTIME] TEXT,
  [REGCHANNEL] TEXT,
  [ISSHOW] TEXT,
  [STATUS] TEXT,
  [PROVINCEID] INTEGER,
  [IDENTITYID] INTEGER,
  [IDENTITY] TEXT,
  [BGURL] TEXT,
  [IDCARD] TEXT,
  [REALNAME] TEXT,
  [INTERESTS] TEXT,
  [MOBILE_TYPE] TEXT,
  [LEVEL] TEXT,
  [DUTY] TEXT,
  [FANS] TEXT,
  [SECRETKEY] TEXT,
  [USERNAME] TEXT,
  [MOBILE] TEXT,
  [USERKEY] TEXT,
  [ENTRYDAY] TEXT,
  [GRADE] TEXT,
  [SCHOOLID] INTEGER,
  [DEPARTMENTID] INTEGER,
  [SPECIALTYID] INTEGER,
  [CLASSID] INTEGER,
  [USERSTATUS] TEXT,
  [CERTIFICATION] TEXT,
  [PIUGINS] TEXT,
  [LEGITIMACY] TEXT,
  [KEYBOARD] TEXT,
  [REGISTERID] TEXT,
  [EXCOLUMN00] TEXT,
  [EXCOLUMN01] TEXT,
  [EXCOLUMN02] TEXT,
  [EXCOLUMN03] TEXT,
  [EXCOLUMN04] TEXT,
  [EXCOLUMN05] TEXT,
  [EXCOLUMN06] TEXT,
  [EXCOLUMN07] TEXT,
  [EXCOLUMN08] TEXT,
  [EXCOLUMN09] TEXT,
  CONSTRAINT [sqlite_autoindex_PUB_USERS_1] PRIMARY KEY ([TRADESCNO], [USERID]));



